spring:
  application:
    name: wallet
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/wallet}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  flyway:
    enabled: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
